
Showing logs for build [32mcramte-jx-qs-python-master-rele-b5zf8-4[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-p2cdk[0m
{"level":"warn","ts":1580936404.2584476,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1580936404.2590015,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mcramte-jx-qs-python-master-rele-b5zf8-4[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-j4fg9[0m
{"level":"warn","ts":1580936405.162547,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1580936405.1664052,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mcramte-jx-qs-python-master-rele-b5zf8-4[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mcramte-jx-qs-python-master-rele-b5zf8-4[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-cramte-jx-qs-python-master-rele-b5zf8-jwtb6[0m
{"level":"warn","ts":1580936411.140955,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1580936414.2189918,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/******/**-qs-python.git @ v0.0.4 in path /workspace/source"}

Showing logs for build [32mcramte-jx-qs-python-master-rele-b5zf8-4[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:118b81488603297af78444cefb5cda05bb9fe168
WARNING: no SHAs to merge, falling back to initial cloned commit

Showing logs for build [32mcramte-jx-qs-python-master-rele-b5zf8-4[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-jx-git-credentials[0m
Generated Git credentials file /workspace/xdg_config/git/credentials

Showing logs for build [32mcramte-jx-qs-python-master-rele-b5zf8-4[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mcramte-jx-qs-python-master-rele-b5zf8-4[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:onbuild        
[36mINFO[0m[0009] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0009] Downloading base image python:onbuild        
[36mINFO[0m[0012] Executing 3 build triggers                   
[36mINFO[0m[0012] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0012] Checking for cached layer docker.io/todo/cache:f96ea06eb1dc1e896fb6ba60e374488f43e9918d4fe1cb30c5f26c8dea340a73... 
[36mINFO[0m[0016] No cached layer found for cmd RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0016] Unpacking rootfs as cmd RUN pip install --no-cache-dir -r requirements.txt requires it. 
[36mINFO[0m[0037] Taking snapshot of full filesystem...        
[36mINFO[0m[0048] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0048] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0048] Taking snapshot of files...                  
[36mINFO[0m[0048] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0048] cmd: /bin/sh                                 
[36mINFO[0m[0048] args: [-c pip install --no-cache-dir -r requirements.txt] 
You are using pip version 10.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[36mINFO[0m[0050] Taking snapshot of full filesystem...        
[36mINFO[0m[0054] Pushing layer docker.io/todo/cache:f96ea06eb1dc1e896fb6ba60e374488f43e9918d4fe1cb30c5f26c8dea340a73 to cache now 
[36mINFO[0m[0054] Using files from context: [/workspace/source] 
[36mINFO[0m[0054] COPY . /usr/src/app                          
[36mINFO[0m[0054] Taking snapshot of files...                  
[36mINFO[0m[0054] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0054] COPY requirements.txt .                      
[36mINFO[0m[0054] Taking snapshot of files...                  
[36mINFO[0m[0054] ENV PORT 8080                                
[36mINFO[0m[0054] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0054] EXPOSE 8080                                  
[36mINFO[0m[0054] cmd: EXPOSE                                  
[36mINFO[0m[0054] Adding exposed port: 8080/tcp                
[36mINFO[0m[0054] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0054] ENTRYPOINT ["python"]                        
[36mINFO[0m[0054] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0054] CMD ["app.py"]                               
[36mINFO[0m[0054] No files changed in this command, skipping snapshotting. 
[33mWARN[0m[0058] error uploading layer to cache: failed to push to destination index.docker.io/todo/cache:f96ea06eb1dc1e896fb6ba60e374488f43e9918d4fe1cb30c5f26c8dea340a73: unsupported status code 401; body:  
2020/02/05 21:01:17 existing blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2020/02/05 21:01:17 existing blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2020/02/05 21:01:17 existing blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2020/02/05 21:01:17 existing blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2020/02/05 21:01:17 existing blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2020/02/05 21:01:17 existing blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2020/02/05 21:01:17 existing blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2020/02/05 21:01:17 existing blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2020/02/05 21:01:17 existing blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2020/02/05 21:01:18 pushed blob: sha256:842fcf18617ca2a458bbf637657c45f24da6426824c812a2d71469c5c18d1e79
2020/02/05 21:01:18 pushed blob: sha256:0e1b2e02d8693a09cf7d9cfeff0da989fcc90561ac7fcb24ee4ea5e7a0a9b4f1
2020/02/05 21:01:19 pushed blob: sha256:df2523ac7e725e8d5fe66b06f1830bd267a32146169ff0ba0d2691689fa09116
2020/02/05 21:01:20 pushed blob: sha256:61a969cbe4d647a3b780d92ae2d3b52a6518fe268a0fafe6769afc78f207ba11
2020/02/05 21:01:21 pushed blob: sha256:dcaa01e682b289cc62382d4e796dadacf579b94e8ea8663c62a6b31e7c6c6336
2020/02/05 21:01:22 index.docker.io/******/**-qs-python:0.0.4: digest: sha256:b7548cbc5ca2174dc026a51d35e9a9905d7fd7c3dbaac8405d052e4d7708271c size: 2385

Showing logs for build [32mcramte-jx-qs-python-master-rele-b5zf8-4[0m stage [32mfrom-build-pack[0m and container [32mstep-build-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mcramte-jx-qs-python-master-rele-b5zf8-4[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-changelog[0m
Converted /workspace/source/charts/**-qs-python to an unshallow repository
Generating change log from git ref e7f40ddbe6db64cabc05e12114e7c4e778c9333c => 7515e12714f39d6cdf2a4ddcf5dccbb53468c2a9
Associating user x-0 in users.jenkins.io with email you@example.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user x-0 in users.jenkins.io
WARNING: Failed to enrich commit b7d66bccad054615add12f431d37906cb2a9a8eb with issues: User.jenkins.io "x-0" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Finding issues in commit messages using git format
WARNING: No release found for ******/**-qs-python and tag v0.0.4 so creating a new release
Updated the release information at https://github.com/******/**-qs-python/releases/tag/v0.0.4
generated: /workspace/source/charts/**-qs-python/templates/release.yaml
Created Release **-qs-python-0-0-4 resource in namespace **
Updating PipelineActivity ******-**-qs-python-master-4 with version 0.0.4
Updated PipelineActivities ******-**-qs-python-master-4 with release notes URL: https://github.com/******/**-qs-python/releases/tag/v0.0.4

Showing logs for build [32mcramte-jx-qs-python-master-rele-b5zf8-4[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-helm-release[0m
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Uploading chart file **-qs-python-0.0.4.tgz to http://jenkins-x-chartmuseum:8080/api/charts
Received 201 response: {"saved":true}

Showing logs for build [32mcramte-jx-qs-python-master-rele-b5zf8-4[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-promote[0m
WARNING: prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/**/issues/2410
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Promoting app **-qs-python version 0.0.4 to namespace **-staging
WARNING: 
WARNING: Waiting for the fork of ******/environment-kind1-staging to appear...
Forked Git repository to https://github.com/******/environment-kind1-staging
Created Pull Request: https://github.com/******-org/environment-kind1-staging/pull/1
Added label updatebot to Pull Request https://github.com/******-org/environment-kind1-staging/pull/1
got git provider status pending from PR https://github.com/******-org/environment-kind1-staging/pull/1
got git provider status pending from PR https://github.com/******-org/environment-kind1-staging/pull/1
got git provider status pending from PR https://github.com/******-org/environment-kind1-staging/pull/1
got git provider status pending from PR https://github.com/******-org/environment-kind1-staging/pull/1
got git provider status pending from PR https://github.com/******-org/environment-kind1-staging/pull/1
Pull Request https://github.com/******-org/environment-kind1-staging/pull/1 is merged at sha 7d03953096897ba4f8970a778ffc52e168f64859
Pull Request merged but we are not waiting for the update pipeline to complete!
WARNING: Could not find the service URL in namespace **-staging for names **-qs-python, **-**-qs-python, **-staging-**-qs-python
